UPDATE triples SET subject_type = 'AI_Agent'     WHERE subject_type = 'Ai_Agent';
UPDATE triples SET object_type  = 'AI_Agent'     WHERE object_type  = 'Ai_Agent';
UPDATE triples SET subject_type = 'API'          WHERE subject_type = 'Api';
UPDATE triples SET object_type  = 'API'          WHERE object_type  = 'Api';
UPDATE triples SET subject_type = 'UI_Component' WHERE subject_type = 'Ui_Component';
UPDATE triples SET object_type  = 'UI_Component' WHERE object_type  = 'Ui_Component';
UPDATE triples SET subject_type = 'UX_Concept'   WHERE subject_type = 'Ux_Concept';
UPDATE triples SET object_type  = 'UX_Concept'   WHERE object_type  = 'Ux_Concept';
UPDATE triples SET subject_type = 'VC_Firm'      WHERE subject_type = 'Vc_Firm';
UPDATE triples SET object_type  = 'VC_Firm'      WHERE object_type  = 'Vc_Firm';
UPDATE triples SET subject_type = 'SaaS'         WHERE subject_type IN ('Saas', 'SAAS');
UPDATE triples SET object_type  = 'SaaS'         WHERE object_type  IN ('Saas', 'SAAS');
UPDATE triples SET subject_type = 'SDK'          WHERE subject_type = 'Sdk';
UPDATE triples SET object_type  = 'SDK'          WHERE object_type  = 'Sdk';
UPDATE triples SET subject_type = 'CLI'          WHERE subject_type = 'Cli';
UPDATE triples SET object_type  = 'CLI'          WHERE object_type  = 'Cli';
UPDATE triples SET subject_type = 'PR'           WHERE subject_type = 'Pr';
UPDATE triples SET object_type  = 'PR'           WHERE object_type  = 'Pr';
UPDATE triples SET subject_type = 'LLC'          WHERE subject_type = 'Llc';
UPDATE triples SET object_type  = 'LLC'          WHERE object_type  = 'Llc';
UPDATE triples SET subject_type = 'KB'           WHERE subject_type = 'Kb';
UPDATE triples SET object_type  = 'KB'           WHERE object_type  = 'Kb';
UPDATE triples SET subject_type = 'URL'          WHERE subject_type = 'Url';
UPDATE triples SET object_type  = 'URL'          WHERE object_type  = 'Url';
UPDATE triples SET subject_type = 'REST_API'     WHERE subject_type = 'Rest_Api';
UPDATE triples SET object_type  = 'REST_API'     WHERE object_type  = 'Rest_Api';
